# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-06 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=50)),
                ('lat', models.FloatField(default=0)),
                ('lon', models.FloatField(default=0)),
                ('valoration', models.FloatField(default=0)),
                ('review', models.IntegerField(default=0)),
                ('users', models.IntegerField(default=0)),
                ('breackfast_price', models.FloatField(default=0)),
                ('launch_price', models.FloatField(default=0)),
                ('dinner_price', models.FloatField(default=0)),
                ('filters', models.CharField(max_length=100)),
            ],
        ),
    ]
