# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='date_birth',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='restaurants',
            field=models.IntegerField(default=0),
        ),
    ]
