# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_restaurant_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='filters',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
